-- 曼波浏览器聊天后端 - Supabase 建表 SQL
-- 在 Supabase 项目 SQL Editor 中粘贴执行

-- 1. 建消息表
create table if not exists messages (
  id bigint generated by default as identity primary key,
  nickname text not null,
  content text not null,
  client_id text,
  create_time timestamptz default now()
);

-- 2. 开启行级安全，允许匿名读写（简易公开聊天，所有人可看可发）
alter table messages enable row level security;
drop policy if exists "anon read" on messages;
drop policy if exists "anon insert" on messages;
create policy "anon read" on messages for select using (true);
create policy "anon insert" on messages for insert with check (true);

-- 3. 自动清理：只保留最近 500 条（可选，防止无限增长）
-- 执行一次即可，或设成 cron
delete from messages where id not in (
  select id from messages order by create_time desc limit 500
);
