plugins {
    id 'com.android.application'
}

android {
    namespace 'com.yby.manbo'
    compileSdk 35

    defaultConfig {
        applicationId 'com.yby.manbo'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
    }
}

dependencies {
}
